### ISSUE TITLE
CrossWire BurJudson module - xulsword display no text for Matthew chapter 1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JohnAustinDev/xulsword#230]
```
Install BurJudson from CrossWire Main.

Select Matthew chapter 1. Only the Introduction is shown. Not the chapter.

cf. Matthew chapter 2 displays OK, as do most other locations.

NB. May require the Padauk font for Burmese script. Already installed in my Win 
7 PC.

btw. Chapter 1 displays OK in Xiphos.






```

Original issue reported on code.google.com by `DFH...@gmail.com` on 15 Feb 2014 at 12:22

Attachments:
* [Screenshot 2014-02-15 12.18.47.png](https://storage.googleapis.com/google-code-attachments/xulsword/issue-230/comment-0/Screenshot 2014-02-15 12.18.47.png)

**Comment by JohnAustinDev** [comment]
This appears to have been fixed in 3.12
