### ISSUE TITLE
update the version at https://addons.mozilla.org

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JohnAustinDev/xulsword#238]
```
As 3.10 doesn't work on latest FF
```

Original issue reported on code.google.com by `ildar.mulyukov` on 22 Jan 2015 at 9:57

**Comment by ildar** [comment]
Can you put the latest version(s) of the xpi to [releases](https://github.com/JohnAustinDev/xulsword/releases) while [Mozilla suspends new version to the addon site](https://addons.mozilla.org/addon/browser-bible-xulsword/reviews/668038/)?
Thanks!

**Comment by JohnAustinDev** [comment]
It may take some time because the Firefox API from 35 to 36 changed in a 
way that requires some refactoring in the xpi. It could take a couple 
weeks or several months- currently unknown.

**Comment by ildar** [comment]
hi! sorry to disturb.
How is the current git HEAD doing? Does it work with the latest Firefox?
If positive, could you please make a preview release?
Thanks in advance!

**Comment by ildar** [comment]
hello!
sadly looking at https://github.com/JohnAustinDev/xulsword/releases
still can't have a preview build to put into "Releases" tab? :(
Best regards...
