### ISSUE TITLE
The large ebible.org repository loads too slowly in module manager

### ISSUE THREAD

**Issue by JohnAustinDev** [JohnAustinDev/xulsword#240]
Sometimes the ebible.org module repository takes so long to load that the busy-script dialog appears.

**Comment by JohnAustinDev** [comment]
This has been fixed in 3.13+

**Comment by ildar** [comment]
Where can I find new releases? The "Releases" tab is empty...

**Comment by JohnAustinDev** [comment]
Here: http://ibtrussia.org/en/pc

or

http://ibtrussia.org/ftpmirror/pub/xulsword/

xulsword 3.13 should be available in the next few days, hopefully.

**Comment by ildar** [comment]
That's great, thanks!
Now what do you think about the FF plugin? Is it End-Of-Line?

**Comment by JohnAustinDev** [comment]
Good question. Firefox is moving toward a more secure plugin ecosystem 
compatible with Google Chrome. This means support for binaries, such as 
xulsword's libxulsword (which is based on CrossWire's C++ SWORD engine) 
is currently in jeopardy. It now takes significant effort to keep 
complicated Add-ons up to date in the quickly evolving Firefox 
ecosystem, so until and unless Mozilla states they will continue support 
for binaries in Firefox Add-ons, I don't think support for the current 
xulsword Firefox Add-on will be maintained.

However, support for xulsword is continuing as usual (xulsword 3.13 is 
based on Firefox 41) and future support for xulsword in its current form 
is still indefinite regardless of Mozilla's rather vague Add-on 
security/support road map.

**Comment by ildar** [comment]
Greetings!
John, Mozilla is not going to drop the old add-ons API right away, see
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
Would you take a time and decide whether you're going to drop it or not?
Thanks!
