### ISSUE TITLE
Firefox 43.0 release 64 bit version - Browser Bible edition of xulsword is incompatible

### ISSUE THREAD

**Issue by DavidHaslam** [JohnAustinDev/xulsword#241]
I just installed the new 64 bit version of Firefox 43.0 and found that the Browser Bible edition of xulsword is incompatible and will be disabled when I restart Firefox.

Not a high priority for me.

Best regards,

David Haslam

**Comment by ildar** [comment]
This is dup of https://github.com/JohnAustinDev/xulsword/issues/238,
also you'd read
https://github.com/JohnAustinDev/xulsword/issues/240#issuecomment-163371385

**Comment by DavidHaslam** [comment]
It's not really a duplicate issue. The add-on was not flagged for being disabled when I was using Firefox 42.0 (32-bit) before I installed the new 64-bit version of Firefox 43.0.

In between those two states, I had actually updated Firefox to 43.0 (32-bit), and even then the add-on was not marked for disable.

I contend therefore that the issue is new in that it relates only to the 64-bit edition of Firefox, which was only released this week. Those earlier issues predate by several months the release of 64-bit.

**Comment by ildar** [comment]
The core issue is that the future of the FF add-on is very questionable.

**Comment by DavidHaslam** [comment]
Understood.

**Comment by DavidHaslam** [comment]
What was eventually decided about the FF add-on?

If it's been abandonned, then this issue might be closed....

**Comment by ildar** [comment]
I don't know about the future of the FF add-on, but duplicate bugs are
better be closed anyway

**Comment by DavidHaslam** [comment]
As you wish.

**Comment by DavidHaslam** [comment]
Please close the issue now.
