### ISSUE TITLE
Fix the MarkDown anomalies in README.md

### ISSUE THREAD

**Issue by DavidHaslam** [JohnAustinDev/xulsword#243]
Some lines in the file begin with one or more # 

These seem to have been intended as MarkDown format but they actually display the # signs.

Some may entail inserting a space.
Others may need the line to be split as well to keep the heading short.

**Comment by JohnAustinDev** [comment]
The markdown used is for GitHub. Markdown isn't very standardized and can be extremely picky so you gotta pick one and go with it. So I don't plan to make changes unless GitHub requires it.

**Comment by DavidHaslam** [comment]
It's not as if GitHub doesn't have a preview option while you're editing, is it?

If you'd originally intended some lines as subheadings by the use of one or more # at the start,
why is not a good idea to make the minor edits to ensure GitHub renders them as you'd wished?

**Comment by JohnAustinDev** [comment]
David,
Maybe I'm missing something? The markdown looks like it should on 
GitHub: https://github.com/JohnAustinDev/xulsword . It is very likely 
that if I change it to fix your viewer (whatever that is?) then it would 
break the above page. I've run into this before with markdown 
unfortunately...
-john

**Comment by DavidHaslam** [comment]
_Mea culpa_.
It's a MarkDown redering bug in the [CodeHub](https://github.com/thedillonb/CodeHub/) app for iOS.
