### ISSUE TITLE
Option filters are all greyed out when I open MK 3.14

### ISSUE THREAD

**Issue by DavidHaslam** [JohnAustinDev/xulsword#245]
I am unable to toggle the filters for **headings**, **footnotes**, **cross ref**s, **dictionary**.

![screenshot 2017-02-07 16 52 48](https://cloud.githubusercontent.com/assets/16325414/22701683/3ea2bb64-ed56-11e6-940d-c3e1cb1a20f0.png)

Also everything in the **View** menu is greyed out!

![screenshot 2017-02-07 16 55 58](https://cloud.githubusercontent.com/assets/16325414/22701743/7342024e-ed56-11e6-8c4c-d99870e29fcf.png)

**Comment by DavidHaslam** [comment]
After deleting the previous file, and opening & closing MK 3.14 here is the new [consoleLog.txt](https://github.com/JohnAustinDev/xulsword/files/771580/consoleLog.txt)

Is there anything reported that I need to fix before you can determine the cause of the error?

**Comment by JohnAustinDev** [comment]
consoleLog.txt shows a timeout is causing a script to be aborted prematurely. I've looked at the offending function, getCSS(), and although it is relatively time consuming, I see no possibility of infinite loops there. The more modules and locales (and custom CSS) that you have, the more getCSS() will be run and the longer it will take. So I'm curious. You can increase your timeout values and restart MK. Go to your MK installation and find the file: IBT/MK/xulsword/defaults/preferences/prefs.js and then add this to the end of it:

pref("dom.max_child_script_run_time", 60);
pref("dom.max_chrome_script_run_time", 60);
pref("dom.max_script_run_time", 60);

Then restart MK and this will increase the timeouts to 60 seconds, which should be far more than enough. If this fixes the problem, let me know how long it takes to open xulsword and how many modules you have installed. I'll see if there are optimizations that can be done to fix it, or if the default timeouts should be increased. If there are still problems, send the consoleLog.txt report after the 60 second timeout and errors.

**Comment by DavidHaslam** [comment]
### Aside 

Yesterday on my PC, everything was running slow. 

After I rebooted, processes seemed to back to normal speed.

**Comment by DavidHaslam** [comment]
### Further note

Not yet moved back the large resources folder to my xulsword profile. 

That would further increase the number of modules to be detected.

**Comment by DavidHaslam** [comment]
I added the three lines to the file called `prefs.js`.

This has solved the problem, but I forgot to use a stop-watch.
After disregarding two modules that wanted unlocking, the option filters were no longer greyed out.

Here is the new [consoleLog.txt](https://github.com/JohnAustinDev/xulsword/files/777640/consoleLog.txt)

There are 428 `.conf` files in my `mods.d` folder.

When I get time, I will try further with the large `resources` folder restored first.
