### ISSUE TITLE
What's involved in the xulsword telemetry?

### ISSUE THREAD

**Issue by DavidHaslam** [JohnAustinDev/xulsword#246]
Does `Toolkit.Telemetry` send any data over the internet?  If not, why is this word used?

cf. All the fuss during 2016 regarding Windows Telemetry and user privacy.

**Comment by JohnAustinDev** [comment]
Mozilla's pref toolkit.telemetry.enabled is false so their telemetry feature is not enabled for xulsword. It should not be accessing the Internet.

**Comment by DavidHaslam** [comment]
Thanks.
