### ISSUE TITLE
Implement libxulsword callbacks

### ISSUE THREAD

**Issue by tomr2k** [JohnAustinDev/xulsword#249]
libxulsword relies on three JavaScript callbacks:

- [ ] uppercase: a JavaScript function that uppercases libxulsword strings.
- [ ] catch exceptions: a JavaScript function that records an exception thrown by a libxulsword function call such that when libxulsword throws an exception, the JavaScript calling logic can disregard the results and act on the exception.
- [ ] report progress: a JavaScript function called by libxulsword to report progress on lengthy operations.

In our current implementation these functions are stubbed out in the module's c++ code ... no call to the JavaScript layer is made.

**Comment by JohnAustinDev** [comment]
These are completed.
