### ISSUE TITLE
cannot get commentary modules to run

### ISSUE THREAD

**Issue by sysstb** [JohnAustinDev/xulsword#278]
I have tried downloading and importing commentary files into both the AppImage and windows application. Both seem to load fine (I get the tab when choosing window and commentary), but no text or menus appear in the window. Thx

**Comment by JohnAustinDev** [comment]
Commentaries work now.

**Comment by sysstb** [comment]
Thanks... I saw the new version today.

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 12, 2023 at 12:51 PM, ***@***.***> wrote:   


Commentaries work now.
